project:
  type: website
  render:
    - "*.qmd"
    - "!archive/"

website:
  title: "Marques-Coelho Bioinformatics Lab"
  description: "Demo projects, experiments, debugging data and so on from the [Atlas of Living Australia (ALA)](https://ala.org.au/)"
  open-graph:
    image: twitter-card-preview_frog-small.png
    image-alt: "A Southern Brown Tree Frog with the ALA Labs logo"
  twitter-card:
    image: twitter-card-preview_frog-small.png
    image-alt: "A Southern Brown Tree Frog with the ALA Labs logo"
    card-style: summary_large_image
  site-url: https://labs.ala.org.au/
  favicon: images/favicon.ico
  navbar:
    background: "#222322"
    foreground: "#FFFFFF"
    title: ""
    search: true
    logo: images/logos/lab_log_reverse.svg
    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
      - href: about/index.qmd
        text: "About"
      - href: research/citations/index.qmd
        text: "Research"
      - href: https://github.com/MCBLab
        icon: github

format:
  html:
    fontsize: 1.15rem
    monofont: Fira Code
    highlight-style: arrow
    css: [theme.css, custom_theme.scss]
    toc: true
    code-overflow: scroll
    linkcolor: "#B8573E"
    include-before-body: _fathom.html



