---
title: "About"
subtitle: Role and membership of the MCB Lab Team
format: 
  html: 
    include-after-body: _footer.html
title-block-banner: "#fcbd27"
title-block-banner-color: body
---

```{r setup}
#| include: false
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
#| include: false
library(htmltools)
source("../R/functions.R")
```


### We are responsible for:  

- Data analysis & reporting on key projects
- Nextflow pipeline development & maintenance
- Outreach & engagement with the research community

# Meet the team

## Lab members

*Click on photos to view their articles and contributions*
```{r}
#| echo: false
tags$div(class = "row",# Create a row for 3 team-member cards
         
create_team_card(
  person_page = "diego_coelho/index.html",
  img_src = "images/logos/diego_image.png",
  name = "Diego M. Coelho",
  text = "Team Leader"
),
create_team_card(
  person_page = "isaac_medeiros/index.html",
  img_src = "https://avatars.githubusercontent.com/u/127994907?v=4",
  name = "Isaac Medeiros",
  text = "Undergraduate"
)
)
```

## External collaborators
*Click on photos to view their articles and contributions*
```{r}
#| echo: false

tags$div(class = "row",# Create a row for 3 team-member cards
         
create_team_card(
  person_page = "julia_apolonio/index.html",
  img_src = "https://avatars.githubusercontent.com/u/19909582?v=4",
  name = "Julia Apolonio",
  text = "Msc candidate"
),
create_team_card(
  person_page = "joao_cav/index.html",
  img_src = "https://avatars.githubusercontent.com/u/43506501?v=4",
  name = "João Cavalcante",
  text = "PhD candidate"
)
)

tags$div(class = "row",# Create a row for 3 team-member cards
         
create_team_card(
  person_page = "gleison_medeiros/index.html",
  img_src = "https://avatars.githubusercontent.com/u/71445184?v=4",
  name = "Gleison Medeiros",
  text = "Msc candidate"
),
create_team_card(
  person_page = "laura_shimohara/index.html",
  img_src = "https://avatars.githubusercontent.com/u/157064283?v=4",
  name = "Laura Shimohara",
  text = "Msc candidate"
)
)

```

